name: Add statistics

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at 00:00 UTC time
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - env:
          GH_TOKEN: ${{ github.token }}
        run: python scripts/update_total_pub_repo.py
      - run: |
          git config user.name "Update stats"
          git config user.email "nicho@scapeville.com"
          git add .
          git commit -m "Stats updated on $(date +'%B %d, %Y, %l:%M %p')"
          git push