name: Lineosaurus

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: nvfp/Line-O-Saurus@0.2.2
        with:
          show-credit: "[1, 3, '4']"
        env:
          GH_TOKEN: ${{ github.token }}