name: Lineosaurus

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: echo $(date +'%Y %b %e, %l:%M %p') > foo123123.txt
      - uses: scapeville/action-git-add-all-then-commit-then-push@0.5.0
        with:
          name: foobar
        env:
          GH_TOKEN: ${{ github.token }}