name: Lineosaurus
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: Lineosaurus/Lineosaurus@v1
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          git-name: Stats update
          git-email: ${{ vars.NICHOLAS_EMAIL }}
          flavor: miniature by nvfp
          ingredients: |
            - banner_path: https://github.com/nvfp/nvfp/raw/main/assets/banner.jpg
            - banner_alt: banner
