name: Lineosaurus

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: scapeville/action-git-add-all-then-commit-then-push@0.1.0