name: Lineosaurus

on:
  # schedule:
  #   - cron: '0 0 * * *'  # Runs daily
  workflow_dispatch:  # Update manually via 'Actions' tab
  push:
    branches: [main]

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # For committing
    steps:
      - uses: nvfp/Line-O-Saurus@v1.0.0b10
        with:
          git-name: Rrrrr
          git-email: nicho@scapeville.com
          only-type: null
          ignore-type: null
          header: assets/Lineosaurus-header.md
          footer: null
          custom-title: |-
            Over _LINES_ROUND_ lines of code stretch through _OWNER_'s repositories
          num-shown: 100
          show-approx: true
          card-titles: null
          card-order: '["line"]'
          prefer-extension: true
          show-credit: true
        env:
          GH_TOKEN: ${{ github.token }}  # For GitHub CLI