name: Lineosaurus

on:
  # schedule:
  #   - cron: '0 0 * * *'  # Runs daily
  workflow_dispatch:  # Update manually via 'Actions' tab
  push:
    branches: [main]

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # For committing
    steps:
      - uses: nvfp/Line-O-Saurus@v1.0.0b3
        with:
          git-name: Test lino
          git-email: nicho@scapeville.com
          only-type: null
          ignore-type: null
          header: assets/Lineosaurus-header.md
          footer: null
          custom-title: |-
            ### ~ Updated on _DATE_ ~

            ### Over _LINES_ROUND_ lines of code stretch through _OWNER_'s repositories.
          num-shown: 30
          show-approx: true
          card-titles: |
            - line: #### title for 'line'
            - type: #### title for 'type'
            - size: #### title for 'size'
            - stat: #### title for 'stat'
            - char: #### title for 'char'
            - star: #### title for 'star'
            - cmit: #### title for 'cmit'
            - file: #### title for 'file'
          card-order: |
            line
            type
            size
            stat
            char
            star
            cmit
            file
          prefer-extension: true
          show-credit: true
        env:
          GH_TOKEN: ${{ github.token }}  # For GitHub CLI