name: Lineosaurus
on: { schedule: [{ cron: '0 0,12 * * *' }], workflow_dispatch: null, push: null }
jobs:
  run:
    runs-on: ubuntu-latest
    permissions: { contents: write }  # for committing
    steps:
      - uses: Lineosaurus/Lineosaurus@v2
        env:
          GH_TOKEN: ${{ github.token }}  # for GitHub CLI
        with:
          nickname: NVfp
          banner: ./assets/banner.jpg
          include_last_activity: true
          gitname: NV and Lino
          gitemail: ${{ vars.MY_EMAIL }}
          credit: true
