name: Lineosaurus

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: nvfp/Line-O-Saurus@0.5.1
        with:
          git-name: Lineosaurus
          git-email: nicho@scapeville.com
        env:
          GH_TOKEN: ${{ github.token }}