name: Lineosaurus
on: { schedule: [{ cron: '0 0 * * *' }], workflow_dispatch: null, push: null }
jobs:
  run:
    runs-on: ubuntu-latest
    permissions: { contents: write }  # for committing
    steps:
      - uses: Lineosaurus/Lineosaurus@v5
        env:
          GH_TOKEN: ${{ github.token }}  # for GitHub CLI
        with:
          nickname: NVfp
          banner1: ./assets/banner.jpg
          banner2: ./assets/banner.jpg
          gitname: NV_Lino
          gitemail: ${{ vars.MY_EMAIL }}
          credit: true
