name: Lineosaurus

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily
  workflow_dispatch:     # Update manually via 'Actions' tab

  ## The line `push:` below is for immediately updating your README.md for its first time.
  ## After you've seen the update, you may want to comment/delete it out.
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # For committing
    steps:
      - uses: Lineosaurus/Lineosaurus@v1
        env:
          GH_TOKEN: ${{ github.token }}  # For GitHub CLI
        with:

          ## required ##

          git-name: Stats update
          git-email: ${{ vars.NICHOLAS_EMAIL }}

          ## options ##

          flavor: miniature by nvfp
          ingredients: |
            - banner_path: https://github.com/nvfp/nvfp/raw/main/assets/dino.jpg
            - banner_alt: dino