name: Lineosaurus

on:
  # schedule:
  #   - cron: '0 0 * * *'  # Runs daily
  workflow_dispatch:  # Update manually via 'Actions' tab
  push:
    branches: [main]

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # For committing
    steps:
      - uses: nvfp/Line-O-Saurus@0.5.7
        with:
          git-name: Test lino
          git-email: nicho@scapeville.com
          only-type: '[".txt", ".md", ".json"]'
          ignore-type: '[.txt, .md, .json]'
          header: null
          footer: null
          custom-title: |-
            ~ Updated on _DATE_ ~

            _LINE_ lines of code stretch through _OWNER_'s repositories.
          num-shown: 3
          show-approx: true
          card-titles: '{"line": "foo", "star": "bar"}'
          card-order: '["line", "star"]'
          prefer-extension: true
          show-credit: false
        env:
          GH_TOKEN: ${{ github.token }}  # For GitHub CLI