name: Lineosaurus

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

env:
  git-name: Lineosaurus
  git-email: nicho@scapeville.com

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: echo $(date +'%Y %b %e, %l:%M %p') > foo123123.txt
      - uses: scapeville/action-git-add-all-then-commit-then-push@v1
        with:
          name: ${{ env.git-name }}
          email: ${{ env.git-email }}
          msg: "Updated on $(date +'%Y %b %e, %l:%M %p')"
        env:
          GH_TOKEN: ${{ github.token }}